added new build configuration - for 2MB linear memory.
* new option in ez80-cc
* new library libcrtexe
* new ld script cpm-2mb.ld

diff --git a/direct-shims/ez80-cc b/direct-shims/ez80-cc
--- a/direct-shims/ez80-cc
+++ b/direct-shims/ez80-cc
@@ -23,6 +23,11 @@ OPTIMISE_TYPE="size"
 # Default library type
 LIB_TYPE="v99x8-standard"
 
+# Set default value for MEM_MODEL
+MEM_MODEL="64KB"
+
+MEM_MODEL_SUPPLIED=0
+
 # Temporary array to hold non-option arguments
 ARGS=()
 
@@ -50,6 +55,16 @@ while [[ "$#" -gt 0 ]]; do
       fi
       shift 2
       ;;
+    --mem-model)
+      if [[ "$2" == "64KB" || "$2" == "2MB" ]]; then
+        MEM_MODEL="$2"
+        MEM_MODEL_SUPPLIED=1
+      else
+        echo "Invalid value for --mem-model. Allowed values are 64KB or 2MB."
+        exit 1
+      fi
+      shift 2
+      ;;
     -D*)
       CLANG_DEFINES+=("$1")
       shift
@@ -69,6 +84,7 @@ while [[ "$#" -gt 0 ]]; do
       echo "  --iquote dir      Specify an additional include directory for the compiler."
       echo "  --optimise type   Specify the optimisation type (size or speed)."
       echo "  --lib type        Specify the library type: v99x8-standard(default) or v99x8-hdmi."
+      echo "  --mem-model type  Specify the memory model: 64KB (default) or 2MB."
       echo "  --help            Display this help message."
       echo
       echo "Arguments:"
@@ -105,10 +121,19 @@ fi
 OUTPUT_BINARY=$1
 
 EXT="${OUTPUT_BINARY##*.}"
-if [ "$(echo "$EXT" | tr '[:upper:]' '[:lower:]')" != "com" ]; then
-  OUTPUT_BINARY="${OUTPUT_BINARY%.*}.com"
+
+if [ "$MEM_MODEL" == "2MB" ]; then
+  if [ "$(echo "$EXT" | tr '[:upper:]' '[:lower:]')" != "exe" ]; then
+    OUTPUT_BINARY="${OUTPUT_BINARY%.*}.exe"
+  else
+    shift
+  fi
 else
-  shift
+  if [ "$(echo "$EXT" | tr '[:upper:]' '[:lower:]')" != "com" ]; then
+    OUTPUT_BINARY="${OUTPUT_BINARY%.*}.com"
+  else
+    shift
+  fi
 fi
 
 if [ -n "$OUTPUT_DIR" ]; then
@@ -135,11 +160,14 @@ if [ "$FILE_TYPES_OK" -eq 0 ]; then
   exit 1
 fi
 
+# Create a unique temporary directory
+TMP_DIR=$(mktemp -d)
+
 # Arrays to hold object files
 OBJECT_FILES=()
 
 cleanup() {
-  rm -f "${OBJECT_FILES[@]}"
+  rm -rf "$TMP_DIR"
 }
 
 trap cleanup EXIT
@@ -148,15 +176,16 @@ trap cleanup EXIT
 for FILE in "$@"; do
   EXT="${FILE##*.}"
   BASENAME="${FILE%.*}"
+  TMP_BASENAME="$TMP_DIR/$(basename "$BASENAME")"
 
   if [ "$EXT" == "c" ]; then
-    echo "Compiling $FILE -> $BASENAME.c.o"
-    ez80-clang ${CFLAGS} ${CLANG_DEFINES} "$FILE"  -c -o  "$BASENAME.c.o"
-    OBJECT_FILES+=("$BASENAME.c.o")
+    echo "Compiling $FILE"
+    ez80-clang ${CFLAGS} ${CLANG_DEFINES} "$FILE"  -c -o  "$TMP_BASENAME.c.o"
+    OBJECT_FILES+=("$TMP_BASENAME.c.o")
   elif [ "$EXT" == "asm" ]; then
-    echo "Assembling $FILE -> $BASENAME.o"
-    ez80-as ${CLANG_DEFINES} -march=ez80+full ${FILE} -o "$BASENAME.o"
-    OBJECT_FILES+=("$BASENAME.o")
+    echo "Assembling $FILE"
+    ez80-as ${CLANG_DEFINES} -march=ez80+full ${FILE} -o "$TMP_BASENAME.o"
+    OBJECT_FILES+=("$TMP_BASENAME.o")
   else
     echo "Unsupported file type: $FILE"
     exit 1
@@ -164,7 +193,12 @@ for FILE in "$@"; do
 done
 
 # Link object files into the final executable binary
-echo "Linking ${OBJECT_FILES[*]} -> $OUTPUT_BINARY"
+echo "Building $OUTPUT_BINARY"
+
+if [ "$MEM_MODEL" == "2MB" ]; then
+  LINKER_SCRIPT=${EZ80_CLANG_LS_PATH}/cpm-2mb.ld
+  LDFLAGS="--whole-archive -lcrtexe --no-whole-archive $LDFLAGS"
+fi
 
 ez80-ld ${CLANG_DEFINES} -T ${LINKER_SCRIPT} ${LDFLAGS} "${OBJECT_FILES[@]}" --start-group -llibc -lcrt -lcpm -l${LIB_TYPE} -lez80 -lmalloc -lio -lez80rc --end-group --oformat binary -o "$OUTPUT_BINARY"
 
